export const cartTypes = {
    TOGGLE_OVERLAY: 'TOGGLE_OVERLAY',
    CLOSE_OVERLAY: 'CLOSE_OVERLAY',
    ADD_TO_CART: 'ADD_TO_CART',
    ADD_FROM_CART: 'ADD_FROM_CART',
    ADD_TO_CART_FROM_CATEGORY_PAGE: 'ADD_TO_CART_FROM_CATEGORY_PAGE',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    CHANGE_SIZE_OR_COLOR: 'CHANGE_SIZE_OR_COLOR',
    SELECT_ATTRIBUTE_FROM_ITEM_PAGE: 'SELECT_ATTRIBUTE_FROM_ITEM_PAGE'
  }