export const cartTypes = {
    TOGGLE_OVERLAY: 'TOGGLE_OVERLAY',
    CLOSE_OVERLAY: 'CLOSE_OVERLAY',
    ADD_TO_CART: 'ADD_TO_CART',
    ADD_FROM_CART: 'ADD_FROM_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    CHANGE_SIZE_OR_COLOR: 'CHANGE_SIZE_OR_COLOR'
  }